[project]
name = "simply"
version = "0.3.4"
description = "Simply: Minimal Code for Frontier LLM Research in JAX"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "absl-py>=2.3.1",
    "clu>=0.0.12",
    "einops>=0.8.1",
    "grain>=0.2.15",
    "orbax>=0.1.9",
    "pylatexenc>=2.10",
    "pytest>=9.0.2",
    "seqio>=0.0.20",
    "sympy>=1.14.0",
    "t5>=0.9.4",
    "tensorboard>=2.19.0,<2.20",
]


[project.optional-dependencies]
gpu = [
    "jax[cuda13]",
]
tpu = [
    "jax[tpu]>=0.8.2",
]
wandb = [
    "wandb>=0.16.0",
]

[tool.setuptools.packages.find]
include = ["simply", "simply.*"]
