[project]
name = "simply"
version = "0.3.4"
description = "Simply: Minimal Code for Frontier LLM Research in JAX"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "absl-py>=2.3.1",
    "einops>=0.8.1",
    "grain>=0.2.15",
    "orbax>=0.1.9",
    "pylatexenc>=2.10",
    "pytest>=9.0.2",
    "sentencepiece>=0.2.0",
    "sympy>=1.14.0",
    "tokenizers>=0.15.0",
    "pandas>=2.3.3",
    "datasets>=4.4.2",
    "pyarrow>=22.0.0",
    "wandb>=0.23.1",
]


[project.optional-dependencies]
gpu = [
    "jax[cuda13]",
]
tpu = [
    "jax[tpu]>=0.8.2",
]
wandb = [
    "wandb>=0.16.0",
]

[tool.setuptools.packages.find]
include = ["simply", "simply.*"]
